#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Wizard state (only the box IP, for re-runs) lives outside the repo.
ENV_FILE="$HOME/.anchor-deploy-wizard-state"

banner "Anchor deploy errands (#24)"

# ── Stage 1: preflight + SSH keys ─────────────────────────────────────────
stage "SSH keys"
say "Two keys: your personal key (you -> the server) and a CI key (GitHub Actions -> the server)."
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "gh isn't logged in, and this wizard writes GitHub secrets."
  say  "Run 'gh auth login' first, then re-run the wizard."
  exit 1
fi
personal_pub=""
for candidate in "$HOME/.ssh/id_ed25519.pub" "$HOME/.ssh/id_rsa.pub"; do
  [[ -f "$candidate" ]] && { personal_pub="$candidate"; break; }
done
if [[ -z "$personal_pub" ]]; then
  say "No personal SSH key found; creating one (no passphrase)."
  ssh-keygen -t ed25519 -f "$HOME/.ssh/id_ed25519" -N "" >/dev/null
  personal_pub="$HOME/.ssh/id_ed25519.pub"
fi
say "Personal key: $personal_pub"
if [[ ! -f "$HOME/.ssh/anchor_ci" ]]; then
  say "Creating the CI key (no passphrase; only GitHub Actions will hold it)."
  ssh-keygen -t ed25519 -C anchor-ci -f "$HOME/.ssh/anchor_ci" -N "" >/dev/null
fi
set_secret ANCHOR_DEPLOY_SSH_KEY "$(cat "$HOME/.ssh/anchor_ci")"
note "The CI private key now lives only in that GitHub secret and in ~/.ssh/anchor_ci."
pause

# ── Stage 2: the Hetzner box ──────────────────────────────────────────────
stage "Hetzner — rent the server"
say "One small VPS (~\$5/month) runs the whole app."
open_url "https://console.hetzner.com/"
step "Sign up if you don't have an account (needs a card; new accounts sometimes wait briefly for verification)."
step "Create a project (call it 'anchor'), then click 'Add Server'."
step "Location: Ashburn, VA.  Image: Ubuntu 24.04.  Type: Shared vCPU x86 -> CPX11."
step "Under SSH keys, click 'Add SSH key' and paste this line:"
printf '\n%s\n\n' "$(cat "$personal_pub")"
step "Create the server, then copy its public IPv4 address."
ask ANCHOR_DEPLOY_HOST "Paste the server's IPv4 address:"
write_env ANCHOR_DEPLOY_HOST "$ANCHOR_DEPLOY_HOST"
say "Waiting for the box to answer on SSH..."
tries=0
until ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new "root@$ANCHOR_DEPLOY_HOST" true 2>/dev/null; do
  tries=$((tries + 1))
  if (( tries >= 24 )); then warn "no SSH answer after 2 minutes — check the IP"; exit 1; fi
  sleep 5
done
say "SSH is up."
# Pin the server's identity so CI never trusts a machine-in-the-middle.
known_hosts="$(ssh-keyscan "$ANCHOR_DEPLOY_HOST" 2>/dev/null || true)"
if [[ -z "$known_hosts" ]]; then
  warn "couldn't read the server's host key — re-run the wizard once the box is reachable"
  exit 1
fi
set_var ANCHOR_DEPLOY_HOST "$ANCHOR_DEPLOY_HOST"
set_var ANCHOR_DEPLOY_KNOWN_HOSTS "$known_hosts"
pause

# ── Stage 3: DNS ──────────────────────────────────────────────────────────
stage "Cloudflare — point the domain at the box"
say "Two DNS records send anchorfilms.app traffic to the new server."
open_url "https://dash.cloudflare.com/"
step "Open anchorfilms.app -> DNS -> Records -> 'Add record'."
step "Type A, name @, IPv4 $ANCHOR_DEPLOY_HOST — and click the orange cloud so it turns GREY ('DNS only')."
note "Grey matters: Caddy on the box fetches its own HTTPS certificate, which fails behind Cloudflare's proxy."
step "Add a second A record the same way with name www."
pause "Both records saved? Press Enter to check them."
for name in anchorfilms.app www.anchorfilms.app; do
  resolved="$(dig +short +time=3 +tries=1 "$name" @1.1.1.1 2>/dev/null | tail -1 || true)"
  if [[ "$resolved" == "$ANCHOR_DEPLOY_HOST" ]]; then
    say "✓ $name -> $resolved"
  else
    warn "$name resolves to '${resolved:-nothing}', expected $ANCHOR_DEPLOY_HOST — check the record (is the cloud grey?)"
  fi
done
pause

# ── Stage 4: R2 backup bucket ─────────────────────────────────────────────
stage "Cloudflare R2 — where nightly backups land"
say "R2 is Cloudflare's file storage; the free tier covers us. Database dumps ship here every night."
open_url "https://dash.cloudflare.com/"
step "In the left sidebar open 'R2 Object Storage' (first time: enable R2 on the free plan; it asks for a card)."
step "Create a bucket named exactly: anchor-backups (location: Automatic)."
step "In the bucket -> Settings, add an object lifecycle rule: delete objects 30 days after upload."
step "Back on the R2 overview, open the API tokens page (labelled 'Manage R2 API Tokens' or similar)."
step "Create a token: permissions 'Object Read & Write', scoped to only the anchor-backups bucket."
say "The token page shows three things the server needs (they go only to the box, never to GitHub):"
note "The account ID is the long hex string in the endpoint URL: https://<account-id>.r2.cloudflarestorage.com"
ask R2_ACCOUNT_ID "Paste the account ID:"
ask R2_ACCESS_KEY_ID "Paste the Access Key ID:"
ask_secret R2_SECRET_ACCESS_KEY "Paste the Secret Access Key (hidden):"
pause

# ── Stage 5: Sentry ───────────────────────────────────────────────────────
stage "Sentry — error reporting"
say "Sentry emails you when the app throws in production. Free tier, two projects (backend + frontend)."
open_url "https://sentry.io/signup/"
step "Create a free account (any org name)."
step "Create a project: platform FastAPI, name it anchor-backend."
step "Copy its DSN — the https://...ingest...sentry.io/... URL on the setup page"
note "(also under Settings -> Projects -> anchor-backend -> Client Keys)."
ask_secret SENTRY_DSN_BACKEND "Paste the anchor-backend DSN (hidden):"
set_secret ANCHOR_SENTRY_DSN "$SENTRY_DSN_BACKEND"
step "Create a second project: platform React, name it anchor-frontend, and copy its DSN."
ask SENTRY_DSN_FRONTEND "Paste the anchor-frontend DSN:"
set_var ANCHOR_SENTRY_DSN_FRONTEND "$SENTRY_DSN_FRONTEND"
pause

# ── Stage 6: remaining GitHub values ──────────────────────────────────────
stage "GitHub — the last two values"
say "Nothing to click here; the wizard sets these itself."
say "Generating a random database password (only Actions and the box ever see it)."
set_secret ANCHOR_POSTGRES_PASSWORD "$(openssl rand -hex 24)"
set_var ANCHOR_DEPLOY_USER "deploy"
pause

# ── Stage 7: bootstrap the box ────────────────────────────────────────────
stage "Server setup"
say "Copying the deploy files to the box and running setup.sh as root."
say "It installs Docker, creates the CI login user, turns on the firewall and the nightly backup timer."
rsync -az --delete deploy/ "root@$ANCHOR_DEPLOY_HOST:/root/anchor-deploy/"
printf '%s\n%s\n%s\n' "$R2_ACCOUNT_ID" "$R2_ACCESS_KEY_ID" "$R2_SECRET_ACCESS_KEY" |
  ssh "root@$ANCHOR_DEPLOY_HOST" "bash /root/anchor-deploy/setup.sh '$(cat "$HOME/.ssh/anchor_ci.pub")'"
say "Checking the pieces:"
if ssh -i "$HOME/.ssh/anchor_ci" -o BatchMode=yes "deploy@$ANCHOR_DEPLOY_HOST" docker ps >/dev/null 2>&1; then
  say "✓ CI can log in as deploy and use Docker"
else
  warn "the deploy user can't run docker over the CI key — re-run this stage"
  exit 1
fi
if [[ "$(ssh "root@$ANCHOR_DEPLOY_HOST" systemctl is-active anchor-backup.timer)" == "active" ]]; then
  say "✓ nightly backup timer is armed"
else
  warn "anchor-backup.timer is not active — check 'systemctl status anchor-backup.timer' on the box"
fi
pause

# ── Stage 8: what happens next ────────────────────────────────────────────
stage "Done — what happens next"
say "Every errand is finished. The rest happens through the pull request:"
step "Merging the deploy PR triggers the first deploy."
step "That first run will fail at 'docker compose pull' — the two images GHCR just"
step "created are private by default. One-time fix, then it never happens again:"
note "  github.com/KyleKDang?tab=packages -> anchor-app -> Package settings -> Change visibility -> Public"
note "  then the same for anchor-caddy, and re-run the failed deploy job."
say "After that, https://anchorfilms.app is live and every merge to main ships itself."
pause "Press Enter to finish."

finish
